### ISSUE TITLE
issues running sinatra 1.4 with rack 1.6

### ISSUE THREAD

**Issue by kares** [jruby/jruby-rack#203]
```
Internal Server Error (500)
Request Method:     GET
Request URL:    http://localhost:8080/jruby_hello_world/

Server handler (trinidad,puma,reel,HTTP,webrick) not found. from C:/apache/tomcat-8.0.21/webapps/jruby_hello_world/WEB-INF/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1781:in `detect_rack_handler' 
from C:/apache/tomcat-8.0.21/webapps/jruby_hello_world/WEB-INF/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1437:in `run!' 
from C:\apache\tomcat-8.0.21\webapps\jruby_hello_world\WEB-INF\config.ru:7:in `(root)' 
from org/jruby/RubyBasicObject.java:1594:in `instance_eval' 
from C:/apache/tomcat-8.0.21/webapps/jruby_hello_world/WEB-INF/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize' 
from C:\apache\tomcat-8.0.21\webapps\jruby_hello_world\WEB-INF\config.ru:1:in `(root)'

You're seeing this error because you use JRuby::Rack::ErrorApp::ShowStatus.
```

sample app at: https://github.com/predatorian3/jruby_hello_world

**Comment by predatorian3** [comment]
https://github.com/predatorian3/jruby_hello_world/issues/1

**Comment by kares** [comment]
turns out the issue is not related to rack 1.6 and is present with 1.5 ... simply the **config.ru** as is won't work since (as the failure suggests) it does rack handler auto-detection, switch to using [`run MySinatra::App`](https://github.com/jruby/jruby-rack/wiki/Sinatra)
