### ISSUE TITLE
FileNotFoundException on WAS 8.0

### ISSUE THREAD

**Issue by kares** [jruby/jruby-rack#79]
while dealing with #75 I noticed the following exception stopping **jruby-rack** from dispatching to rails

```
[12/28/11 20:43:54:431 CET] 00000018 filter        E com.ibm.ws.webcontainer.filter.FilterInstanceWrapper service SRVE8109W: Uncaught exception thrown by filter RackFilter: java.io.FileNotFoundException: SRVE0190E: File not found: /users.html
    at com.ibm.ws.webcontainer.extension.DefaultExtensionProcessor._processEDR(DefaultExtensionProcessor.java:874)
    at com.ibm.ws.webcontainer.extension.DefaultExtensionProcessor.processEDR(DefaultExtensionProcessor.java:855)
    at com.ibm.ws.webcontainer.extension.DefaultExtensionProcessor.handleRequest(DefaultExtensionProcessor.java:433)
    at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:125)
    at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:92)
    at org.jruby.rack.RackFilter.isDoDispatch(RackFilter.java:47)
    at org.jruby.rack.AbstractFilter.doFilter(AbstractFilter.java:30)
    at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:192)
    at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:89)
    at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:919)
    at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1016)
    at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:3703)
    at com.ibm.ws.webcontainer.webapp.WebGroup.handleRequest(WebGroup.java:304)
    at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:953)
    at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1655)
    at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:195)
    at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:452)
    at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:511)
    at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:305)
    at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.ready(HttpInboundLink.java:276)
    at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:214)
    at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:113)
    at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:165)
    at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
    at com.ibm.io.async.AsyncChannelFuture$1.run(AsyncChannelFuture.java:205)
    at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1650)
```

coming from the filter chain https://github.com/jruby/jruby-rack/blob/master/src/main/java/org/jruby/rack/RackFilter.java#L47
while attempting to add .html to the `/rails_root/users` path, now there's an easy fix for this it just got me confused a bit ...

is it correct for me to surround the `chain.doFilter` invocation into a `try {} catch (FNFE)` 
or am I missing something obvious ?
if I recall correctly WAS is playing here a bit too **smart** am I right // cc @calavera @nicksieger ?

**Comment by lupitagares** [comment]
Hi i am trying to fix an incident in my job, the log shows the same exception:

com.ibm.ws.webcontainer.filter.filterinstancewrapper service SRVE8109W: Uncaught exception thrown by filter action2: java.io.FileNotFoundException: xxxx SRVE0190E: File not found

and i don't know what is that thing?, where it comes from?, nothing! can you help me? chriszhang how did you solve this issue?
thanks a lot!
